// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ZynstormECFPlatform.Data;

#nullable disable

namespace ZynstormECFPlatform.Data.Migrations
{
    [DbContext(typeof(StorageContext))]
    [Migration("20260324013313_InitialDb")]
    partial class InitialDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ZynstormECFPlatform.Core.Entities.ApiKey", b =>
                {
                    b.Property<int>("ApiKeyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ApiKeyId"));

                    b.Property<string>("Apikey")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("text");

                    b.Property<int?>("ClientBrancheId")
                        .HasColumnType("integer");

                    b.Property<int>("ClientId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedTimeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GuidId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(450)
                        .IsUnicode(false)
                        .HasColumnType("character varying(450)")
                        .HasDefaultValue("gen_random_uuid()");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastUpdateUtc")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SecretKey")
                        .IsUnicode(false)
                        .HasColumnType("text");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer");

                    b.HasKey("ApiKeyId");

                    b.HasIndex("ClientId");

                    b.HasIndex("StatusId");

                    b.ToTable("ApiKey");
                });

            modelBuilder.Entity("ZynstormECFPlatform.Core.Entities.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ClientId"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedTimeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("GuidId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(450)
                        .IsUnicode(false)
                        .HasColumnType("character varying(450)")
                        .HasDefaultValue("gen_random_uuid()");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastUpdateUtc")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Rnc")
                        .IsRequired()
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("RNC");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer");

                    b.HasKey("ClientId");

                    b.HasIndex("StatusId");

                    b.ToTable("Client");
                });

            modelBuilder.Entity("ZynstormECFPlatform.Core.Entities.ClientBranche", b =>
                {
                    b.Property<int>("ClientBrancheId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ClientBrancheId"));

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("ClientId")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedTimeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("GuidId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(450)
                        .IsUnicode(false)
                        .HasColumnType("character varying(450)")
                        .HasDefaultValue("gen_random_uuid()");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsMain")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastUpdateUtc")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer");

                    b.HasKey("ClientBrancheId");

                    b.HasIndex("ClientId");

                    b.HasIndex("StatusId");

                    b.ToTable("ClientBranche");
                });

            modelBuilder.Entity("ZynstormECFPlatform.Core.Entities.ClientCallBack", b =>
                {
                    b.Property<int>("ClientCallBackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ClientCallBackId"));

                    b.Property<int?>("ApiKeyId")
                        .HasColumnType("integer");

                    b.Property<int?>("ClientBrancheId")
                        .HasColumnType("integer");

                    b.Property<int>("ClientId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedTimeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GuidId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(450)
                        .IsUnicode(false)
                        .HasColumnType("character varying(450)")
                        .HasDefaultValue("gen_random_uuid()");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastUpdateUtc")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Secret")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("character varying(300)");

                    b.HasKey("ClientCallBackId");

                    b.HasIndex("ApiKeyId");

                    b.HasIndex("ClientBrancheId");

                    b.HasIndex("ClientId");

                    b.HasIndex("StatusId");

                    b.ToTable("ClientCallBack");
                });

            modelBuilder.Entity("ZynstormECFPlatform.Core.Entities.ClientCertificate", b =>
                {
                    b.Property<int>("ClientCertificateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ClientCertificateId"));

                    b.Property<string>("Certificate")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("text");

                    b.Property<int>("ClientId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedTimeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpirationDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GuidId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(450)
                        .IsUnicode(false)
                        .HasColumnType("character varying(450)")
                        .HasDefaultValue("gen_random_uuid()");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastUpdateUtc")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Password")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("text");

                    b.Property<string>("Thumbprint")
                        .IsUnicode(false)
                        .HasColumnType("text");

                    b.HasKey("ClientCertificateId");

                    b.HasIndex("ClientId");

                    b.ToTable("ClientCertificate");
                });

            modelBuilder.Entity("ZynstormECFPlatform.Core.Entities.Currency", b =>
                {
                    b.Property<int>("CurrencyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CurrencyId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("DeletedTimeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GuidId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(450)
                        .IsUnicode(false)
                        .HasColumnType("character varying(450)")
                        .HasDefaultValue("gen_random_uuid()");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastUpdateUtc")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)");

                    b.HasKey("CurrencyId");

                    b.ToTable("Currency");
                });

            modelBuilder.Entity("ZynstormECFPlatform.Core.Entities.DGIIUnit", b =>
                {
                    b.Property<int>("DGIIUnitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DGIIUnitId"));

                    b.Property<int>("DGIICode")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedTimeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GuidId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(450)
                        .IsUnicode(false)
                        .HasColumnType("character varying(450)")
                        .HasDefaultValue("gen_random_uuid()");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastUpdateUtc")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)");

                    b.HasKey("DGIIUnitId");

                    b.ToTable("DGIIUnit");
                });

            modelBuilder.Entity("ZynstormECFPlatform.Core.Entities.EcfDocument", b =>
                {
                    b.Property<int>("EcfDocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EcfDocumentId"));

                    b.Property<int>("ApiKeyId")
                        .HasColumnType("integer");

                    b.Property<int>("ClientBrancheId")
                        .HasColumnType("integer");

                    b.Property<int>("ClientId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("CurrencyId")
                        .HasColumnType("integer");

                    b.Property<string>("CustomerAddress")
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("CustomerEmail")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CustomerRnc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("DeletedTimeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EcfStatusId")
                        .HasColumnType("integer");

                    b.Property<int>("EcfTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("ExternalReference")
                        .IsRequired()
                        .HasMaxLength(70)
                        .IsUnicode(false)
                        .HasColumnType("character varying(70)");

                    b.Property<string>("GuidId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(450)
                        .IsUnicode(false)
                        .HasColumnType("character varying(450)")
                        .HasDefaultValue("gen_random_uuid()");

                    b.Property<string>("HangfireJobId")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("IssueDateUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<decimal>("Itbistotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime?>("LastUpdateUtc")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Ncf")
                        .IsRequired()
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("character varying(80)");

                    b.Property<decimal>("SubTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("EcfDocumentId");

                    b.HasIndex("ApiKeyId");

                    b.HasIndex("ClientBrancheId");

                    b.HasIndex("ClientId");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("EcfStatusId");

                    b.HasIndex("EcfTypeId");

                    b.ToTable("EcfDocument");
                });

            modelBuilder.Entity("ZynstormECFPlatform.Core.Entities.EcfDocumentDetail", b =>
                {
                    b.Property<int>("EcfDocumentDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EcfDocumentDetailId"));

                    b.Property<DateTime?>("DeletedTimeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("Discount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("EcfDocumentId")
                        .HasColumnType("integer");

                    b.Property<string>("GuidId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(450)
                        .IsUnicode(false)
                        .HasColumnType("character varying(450)")
                        .HasDefaultValue("gen_random_uuid()");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<decimal>("ItbisAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("ItbisPercentage")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime?>("LastUpdateUtc")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LineNumber")
                        .HasColumnType("integer");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("SubTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("UnitCode")
                        .HasColumnType("integer");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("EcfDocumentDetailId");

                    b.HasIndex("EcfDocumentId");

                    b.ToTable("EcfDocumentDetail");
                });

            modelBuilder.Entity("ZynstormECFPlatform.Core.Entities.EcfDocumentTotal", b =>
                {
                    b.Property<int>("EcfDocumentId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedTimeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("DiscountTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("EcfDocumentTotalId")
                        .HasColumnType("integer");

                    b.Property<decimal>("ExemptTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("GuidId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(450)
                        .IsUnicode(false)
                        .HasColumnType("character varying(450)")
                        .HasDefaultValue("gen_random_uuid()");

                    b.Property<decimal>("ITBISTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18, 2)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastUpdateUtc")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("TaxableTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("EcfDocumentId");

                    b.ToTable("EcfDocumentTotal");
                });

            modelBuilder.Entity("ZynstormECFPlatform.Core.Entities.EcfStatus", b =>
                {
                    b.Property<int>("EcfStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EcfStatusId"));

                    b.Property<DateTime?>("DeletedTimeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GuidId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(450)
                        .IsUnicode(false)
                        .HasColumnType("character varying(450)")
                        .HasDefaultValue("gen_random_uuid()");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastUpdateUtc")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)");

                    b.HasKey("EcfStatusId");

                    b.ToTable("EcfStatus");

                    b.HasData(
                        new
                        {
                            EcfStatusId = 1,
                            IsDeleted = false,
                            Name = "Created"
                        },
                        new
                        {
                            EcfStatusId = 2,
                            IsDeleted = false,
                            Name = "Validating"
                        },
                        new
                        {
                            EcfStatusId = 3,
                            IsDeleted = false,
                            Name = "ValidationFailed"
                        },
                        new
                        {
                            EcfStatusId = 4,
                            IsDeleted = false,
                            Name = "ReadyToSign"
                        },
                        new
                        {
                            EcfStatusId = 5,
                            IsDeleted = false,
                            Name = "Signing"
                        },
                        new
                        {
                            EcfStatusId = 6,
                            IsDeleted = false,
                            Name = "Signed"
                        },
                        new
                        {
                            EcfStatusId = 7,
                            IsDeleted = false,
                            Name = "SendPending"
                        },
                        new
                        {
                            EcfStatusId = 8,
                            IsDeleted = false,
                            Name = "Sending"
                        },
                        new
                        {
                            EcfStatusId = 9,
                            IsDeleted = false,
                            Name = "Sent"
                        },
                        new
                        {
                            EcfStatusId = 10,
                            IsDeleted = false,
                            Name = "Accepted"
                        },
                        new
                        {
                            EcfStatusId = 11,
                            IsDeleted = false,
                            Name = "Rejected"
                        },
                        new
                        {
                            EcfStatusId = 12,
                            IsDeleted = false,
                            Name = "Error"
                        },
                        new
                        {
                            EcfStatusId = 13,
                            IsDeleted = false,
                            Name = "Cancelled"
                        });
                });

            modelBuilder.Entity("ZynstormECFPlatform.Core.Entities.EcfStatusHistory", b =>
                {
                    b.Property<int>("EcfStatusHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EcfStatusHistoryId"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedTimeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EcfDocumentId")
                        .HasColumnType("integer");

                    b.Property<int>("EcfStatusId")
                        .HasColumnType("integer");

                    b.Property<string>("GuidId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(450)
                        .IsUnicode(false)
                        .HasColumnType("character varying(450)")
                        .HasDefaultValue("gen_random_uuid()");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastUpdateUtc")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("EcfStatusHistoryId");

                    b.HasIndex("EcfDocumentId");

                    b.HasIndex("EcfStatusId");

                    b.ToTable("EcfStatusHistory");
                });

            modelBuilder.Entity("ZynstormECFPlatform.Core.Entities.EcfTransmission", b =>
                {
                    b.Property<int>("EcfTransmissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EcfTransmissionId"));

                    b.Property<int?>("AttemptNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedTimeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EcfDocumentId")
                        .HasColumnType("integer");

                    b.Property<int>("EcfStatusId")
                        .HasColumnType("integer");

                    b.Property<string>("GuidId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(450)
                        .IsUnicode(false)
                        .HasColumnType("character varying(450)")
                        .HasDefaultValue("gen_random_uuid()");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastUpdateUtc")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RequestPayload")
                        .HasColumnType("text");

                    b.Property<string>("ResponseCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ResponseMessage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResponsePayload")
                        .HasColumnType("text");

                    b.Property<DateTime>("SentAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean");

                    b.Property<string>("TrackId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)");

                    b.HasKey("EcfTransmissionId");

                    b.HasIndex("EcfDocumentId");

                    b.HasIndex("EcfStatusId");

                    b.ToTable("EcfTransmission");
                });

            modelBuilder.Entity("ZynstormECFPlatform.Core.Entities.EcfType", b =>
                {
                    b.Property<int>("EcfTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EcfTypeId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime?>("DeletedTimeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GuidId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(450)
                        .IsUnicode(false)
                        .HasColumnType("character varying(450)")
                        .HasDefaultValue("gen_random_uuid()");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastUpdateUtc")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)");

                    b.HasKey("EcfTypeId");

                    b.ToTable("EcfType");
                });

            modelBuilder.Entity("ZynstormECFPlatform.Core.Entities.EcfXmlDocument", b =>
                {
                    b.Property<int>("EcfXmlDocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EcfXmlDocumentId"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedTimeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EcfDocumentId")
                        .HasColumnType("integer");

                    b.Property<string>("GuidId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(450)
                        .IsUnicode(false)
                        .HasColumnType("character varying(450)")
                        .HasDefaultValue("gen_random_uuid()");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastUpdateUtc")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("XmlSigned")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("XmlUnsigned")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("EcfXmlDocumentId");

                    b.HasIndex("EcfDocumentId");

                    b.ToTable("EcfXmlDocument");
                });

            modelBuilder.Entity("ZynstormECFPlatform.Core.Entities.Role", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("ZynstormECFPlatform.Core.Entities.Status", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StatusId"));

                    b.Property<DateTime?>("DeletedTimeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GuidId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(450)
                        .IsUnicode(false)
                        .HasColumnType("character varying(450)")
                        .HasDefaultValue("gen_random_uuid()");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastUpdateUtc")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)");

                    b.HasKey("StatusId");

                    b.ToTable("Status");

                    b.HasData(
                        new
                        {
                            StatusId = 1,
                            IsDeleted = false,
                            Name = "Active"
                        },
                        new
                        {
                            StatusId = 2,
                            IsDeleted = false,
                            Name = "Inactive"
                        },
                        new
                        {
                            StatusId = 3,
                            IsDeleted = false,
                            Name = "Suspended"
                        },
                        new
                        {
                            StatusId = 4,
                            IsDeleted = false,
                            Name = "Deleted"
                        });
                });

            modelBuilder.Entity("ZynstormECFPlatform.Core.Entities.SystemLog", b =>
                {
                    b.Property<int>("SystemLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SystemLogId"));

                    b.Property<int>("ClientId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreateAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedTimeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EcfDocumentId")
                        .HasColumnType("integer");

                    b.Property<string>("Exception")
                        .HasColumnType("text");

                    b.Property<string>("GuidId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(450)
                        .IsUnicode(false)
                        .HasColumnType("character varying(450)")
                        .HasDefaultValue("gen_random_uuid()");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastUpdateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LogLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("SystemLogId");

                    b.HasIndex("ClientId");

                    b.HasIndex("EcfDocumentId");

                    b.ToTable("SystemLog");
                });

            modelBuilder.Entity("ZynstormECFPlatform.Core.Entities.UseClient", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .IsUnicode(false)
                        .HasColumnType("character varying(450)");

                    b.Property<int>("ClientId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedTimeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GuidId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(450)
                        .IsUnicode(false)
                        .HasColumnType("character varying(450)")
                        .HasDefaultValue("gen_random_uuid()");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastUpdateUtc")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "ClientId");

                    b.HasIndex("ClientId");

                    b.ToTable("UseClient");
                });

            modelBuilder.Entity("ZynstormECFPlatform.Core.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedTimeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("GuidId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("LastUpdateUtc")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("ZynstormECFPlatform.Core.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ZynstormECFPlatform.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ZynstormECFPlatform.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("ZynstormECFPlatform.Core.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZynstormECFPlatform.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ZynstormECFPlatform.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ZynstormECFPlatform.Core.Entities.ApiKey", b =>
                {
                    b.HasOne("ZynstormECFPlatform.Core.Entities.Client", "Client")
                        .WithMany("ApiKeys")
                        .HasForeignKey("ClientId")
                        .IsRequired()
                        .HasConstraintName("FK_ApiKey_Client");

                    b.HasOne("ZynstormECFPlatform.Core.Entities.Status", "Status")
                        .WithMany("ApiKeys")
                        .HasForeignKey("StatusId")
                        .IsRequired()
                        .HasConstraintName("FK_ApiKey_Status");

                    b.Navigation("Client");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("ZynstormECFPlatform.Core.Entities.Client", b =>
                {
                    b.HasOne("ZynstormECFPlatform.Core.Entities.Status", "Status")
                        .WithMany("Clients")
                        .HasForeignKey("StatusId")
                        .IsRequired()
                        .HasConstraintName("FK_Client_Status");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("ZynstormECFPlatform.Core.Entities.ClientBranche", b =>
                {
                    b.HasOne("ZynstormECFPlatform.Core.Entities.Client", "Client")
                        .WithMany("ClientBranches")
                        .HasForeignKey("ClientId")
                        .IsRequired()
                        .HasConstraintName("FK_ClientBranche_Client");

                    b.HasOne("ZynstormECFPlatform.Core.Entities.Status", "Status")
                        .WithMany("ClientBranches")
                        .HasForeignKey("StatusId")
                        .IsRequired()
                        .HasConstraintName("FK_ClientBranche_Status");

                    b.Navigation("Client");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("ZynstormECFPlatform.Core.Entities.ClientCallBack", b =>
                {
                    b.HasOne("ZynstormECFPlatform.Core.Entities.ApiKey", "ApiKey")
                        .WithMany("ClientCallBacks")
                        .HasForeignKey("ApiKeyId")
                        .HasConstraintName("FK_ClientCallBack_ApiKey");

                    b.HasOne("ZynstormECFPlatform.Core.Entities.ClientBranche", "ClientBranche")
                        .WithMany("ClientCallBacks")
                        .HasForeignKey("ClientBrancheId")
                        .HasConstraintName("FK_ClientCallBack_ClientBranche");

                    b.HasOne("ZynstormECFPlatform.Core.Entities.Client", "Client")
                        .WithMany("ClientCallBacks")
                        .HasForeignKey("ClientId")
                        .IsRequired()
                        .HasConstraintName("FK_ClientCallBack_Client");

                    b.HasOne("ZynstormECFPlatform.Core.Entities.Status", "Status")
                        .WithMany("ClientCallBacks")
                        .HasForeignKey("StatusId")
                        .IsRequired()
                        .HasConstraintName("FK_ClientCallBack_Status");

                    b.Navigation("ApiKey");

                    b.Navigation("Client");

                    b.Navigation("ClientBranche");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("ZynstormECFPlatform.Core.Entities.ClientCertificate", b =>
                {
                    b.HasOne("ZynstormECFPlatform.Core.Entities.Client", "Client")
                        .WithMany("ClientCertificates")
                        .HasForeignKey("ClientId")
                        .IsRequired()
                        .HasConstraintName("FK_ClientCertificate_Client");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("ZynstormECFPlatform.Core.Entities.EcfDocument", b =>
                {
                    b.HasOne("ZynstormECFPlatform.Core.Entities.ApiKey", "ApiKey")
                        .WithMany("EcfDocuments")
                        .HasForeignKey("ApiKeyId")
                        .IsRequired()
                        .HasConstraintName("FK_EcfDocument_ApiKey");

                    b.HasOne("ZynstormECFPlatform.Core.Entities.ClientBranche", "ClientBranche")
                        .WithMany("EcfDocuments")
                        .HasForeignKey("ClientBrancheId")
                        .IsRequired()
                        .HasConstraintName("FK_EcfDocument_ClientBranche");

                    b.HasOne("ZynstormECFPlatform.Core.Entities.Client", "Client")
                        .WithMany("EcfDocuments")
                        .HasForeignKey("ClientId")
                        .IsRequired()
                        .HasConstraintName("FK_EcfDocument_Client");

                    b.HasOne("ZynstormECFPlatform.Core.Entities.Currency", "Currency")
                        .WithMany("EcfDocuments")
                        .HasForeignKey("CurrencyId")
                        .IsRequired()
                        .HasConstraintName("FK_EcfDocument_Currency");

                    b.HasOne("ZynstormECFPlatform.Core.Entities.EcfStatus", "EcfStatus")
                        .WithMany("EcfDocuments")
                        .HasForeignKey("EcfStatusId")
                        .IsRequired()
                        .HasConstraintName("FK_EcfDocument_EcfStatus");

                    b.HasOne("ZynstormECFPlatform.Core.Entities.EcfType", "EcfType")
                        .WithMany("EcfDocuments")
                        .HasForeignKey("EcfTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_EcfDocument_EcfType");

                    b.Navigation("ApiKey");

                    b.Navigation("Client");

                    b.Navigation("ClientBranche");

                    b.Navigation("Currency");

                    b.Navigation("EcfStatus");

                    b.Navigation("EcfType");
                });

            modelBuilder.Entity("ZynstormECFPlatform.Core.Entities.EcfDocumentDetail", b =>
                {
                    b.HasOne("ZynstormECFPlatform.Core.Entities.EcfDocument", "EcfDocument")
                        .WithMany("EcfDocumentDetails")
                        .HasForeignKey("EcfDocumentId")
                        .IsRequired()
                        .HasConstraintName("FK_EcfDocumentDetail_EcfDocument");

                    b.Navigation("EcfDocument");
                });

            modelBuilder.Entity("ZynstormECFPlatform.Core.Entities.EcfDocumentTotal", b =>
                {
                    b.HasOne("ZynstormECFPlatform.Core.Entities.EcfDocument", "EcfDocument")
                        .WithMany("EcfDocumentTotals")
                        .HasForeignKey("EcfDocumentId")
                        .IsRequired()
                        .HasConstraintName("FK_EcfDocumentTotal_EcfDocument");

                    b.Navigation("EcfDocument");
                });

            modelBuilder.Entity("ZynstormECFPlatform.Core.Entities.EcfStatusHistory", b =>
                {
                    b.HasOne("ZynstormECFPlatform.Core.Entities.EcfDocument", "EcfDocument")
                        .WithMany("EcfStatusHistories")
                        .HasForeignKey("EcfDocumentId")
                        .IsRequired()
                        .HasConstraintName("FK_EcfStatusHistory_EcfDocument");

                    b.HasOne("ZynstormECFPlatform.Core.Entities.EcfStatus", "EcfStatus")
                        .WithMany("EcfStatusHistories")
                        .HasForeignKey("EcfStatusId")
                        .IsRequired()
                        .HasConstraintName("FK_EcfStatusHistory_EcfStatus");

                    b.Navigation("EcfDocument");

                    b.Navigation("EcfStatus");
                });

            modelBuilder.Entity("ZynstormECFPlatform.Core.Entities.EcfTransmission", b =>
                {
                    b.HasOne("ZynstormECFPlatform.Core.Entities.EcfDocument", "EcfDocument")
                        .WithMany("EcfTransmissions")
                        .HasForeignKey("EcfDocumentId")
                        .IsRequired()
                        .HasConstraintName("FK_EcfTransmission_EcfDocument");

                    b.HasOne("ZynstormECFPlatform.Core.Entities.EcfStatus", "EcfStatus")
                        .WithMany("EcfTransmissions")
                        .HasForeignKey("EcfStatusId")
                        .IsRequired()
                        .HasConstraintName("FK_EcfTransmission_EcfStatus");

                    b.Navigation("EcfDocument");

                    b.Navigation("EcfStatus");
                });

            modelBuilder.Entity("ZynstormECFPlatform.Core.Entities.EcfXmlDocument", b =>
                {
                    b.HasOne("ZynstormECFPlatform.Core.Entities.EcfDocument", "EcfDocument")
                        .WithMany("EcfXmlDocuments")
                        .HasForeignKey("EcfDocumentId")
                        .IsRequired()
                        .HasConstraintName("FK_EcfXmlDocument_EcfDocument");

                    b.Navigation("EcfDocument");
                });

            modelBuilder.Entity("ZynstormECFPlatform.Core.Entities.SystemLog", b =>
                {
                    b.HasOne("ZynstormECFPlatform.Core.Entities.Client", "Client")
                        .WithMany("SystemLogs")
                        .HasForeignKey("ClientId")
                        .IsRequired()
                        .HasConstraintName("FK_SystemLog_Client");

                    b.HasOne("ZynstormECFPlatform.Core.Entities.EcfDocument", "EcfDocument")
                        .WithMany("SystemLogs")
                        .HasForeignKey("EcfDocumentId")
                        .IsRequired()
                        .HasConstraintName("FK_SystemLog_EcfDocument");

                    b.Navigation("Client");

                    b.Navigation("EcfDocument");
                });

            modelBuilder.Entity("ZynstormECFPlatform.Core.Entities.UseClient", b =>
                {
                    b.HasOne("ZynstormECFPlatform.Core.Entities.Client", "Client")
                        .WithMany("UseClients")
                        .HasForeignKey("ClientId")
                        .IsRequired()
                        .HasConstraintName("FK_UseClient_Client");

                    b.HasOne("ZynstormECFPlatform.Core.Entities.User", "User")
                        .WithMany("UseClients")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_UseClient_User");

                    b.Navigation("Client");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ZynstormECFPlatform.Core.Entities.ApiKey", b =>
                {
                    b.Navigation("ClientCallBacks");

                    b.Navigation("EcfDocuments");
                });

            modelBuilder.Entity("ZynstormECFPlatform.Core.Entities.Client", b =>
                {
                    b.Navigation("ApiKeys");

                    b.Navigation("ClientBranches");

                    b.Navigation("ClientCallBacks");

                    b.Navigation("ClientCertificates");

                    b.Navigation("EcfDocuments");

                    b.Navigation("SystemLogs");

                    b.Navigation("UseClients");
                });

            modelBuilder.Entity("ZynstormECFPlatform.Core.Entities.ClientBranche", b =>
                {
                    b.Navigation("ClientCallBacks");

                    b.Navigation("EcfDocuments");
                });

            modelBuilder.Entity("ZynstormECFPlatform.Core.Entities.Currency", b =>
                {
                    b.Navigation("EcfDocuments");
                });

            modelBuilder.Entity("ZynstormECFPlatform.Core.Entities.EcfDocument", b =>
                {
                    b.Navigation("EcfDocumentDetails");

                    b.Navigation("EcfDocumentTotals");

                    b.Navigation("EcfStatusHistories");

                    b.Navigation("EcfTransmissions");

                    b.Navigation("EcfXmlDocuments");

                    b.Navigation("SystemLogs");
                });

            modelBuilder.Entity("ZynstormECFPlatform.Core.Entities.EcfStatus", b =>
                {
                    b.Navigation("EcfDocuments");

                    b.Navigation("EcfStatusHistories");

                    b.Navigation("EcfTransmissions");
                });

            modelBuilder.Entity("ZynstormECFPlatform.Core.Entities.EcfType", b =>
                {
                    b.Navigation("EcfDocuments");
                });

            modelBuilder.Entity("ZynstormECFPlatform.Core.Entities.Status", b =>
                {
                    b.Navigation("ApiKeys");

                    b.Navigation("ClientBranches");

                    b.Navigation("ClientCallBacks");

                    b.Navigation("Clients");
                });

            modelBuilder.Entity("ZynstormECFPlatform.Core.Entities.User", b =>
                {
                    b.Navigation("UseClients");
                });
#pragma warning restore 612, 618
        }
    }
}
